### ISSUE TITLE
globalConnectedID appears to not be consistent across subprocesses for some sets.

### ISSUE THREAD

**Issue by rileyvickers** [tmweigand/PMMoTo#17] opened 2023-03-09 23:10 UTC
In a few cases, the globalConnectedID list for sets shared by two processors is not identical.

Fixed for global analysis by joining the globalConnectedID lists into one and retaining unique globalIDs in the list.

In the attached, dataOut contains results when the lists are not combined, instead only the first instance is kept. dataOut_fix contains results when the lists are combined as described above.
[dataOut.zip](https://github.com/tmweigand/PMMoTo/files/10937042/dataOut.zip)
[dataOut_fix.zip](https://github.com/tmweigand/PMMoTo/files/10937043/dataOut_fix.zip)

**Comment by tmweigand** [comment] 2023-03-10 01:58
I just merged your recent pull request and I am looking for the section of code where you check the globalConnectedSets and I cannot find it. Can you push your code to your rv branch so I can look at it.

**Comment by rileyvickers** [comment] 2023-03-10 02:06
Just pushed, FYI it looks like you accidentally removed distance.pyx in a commit of the last pull request

**Comment by tmweigand** [comment] 2023-03-10 02:07
ha...oops. fixing now. Thanks

**Comment by tmweigand** [comment] 2023-03-10 02:43
It seems like the issue is when multiple localIDs point to the same globalID. Working on a solution.

**Comment by rileyvickers** [comment] 2023-03-20 18:02
Recording this here so I don't forget to mention at some point:

Similarly, depending on the need for speed, it may be helpful to update the min and max distances for a set split across processors to all owning processors, that way trim flags based on size accessibility can be set locally. 

I will likely address this comment myself, as I think it will be best to do the size accessibility trimming locally, then size accessibility path creation globally. But I will start simple by doing everything globally.

**Comment by tmweigand** [comment] 2023-03-23 19:17
Just wanted to provide an update that I am working on this but found another bug. It has to do with matching boundary nodes in the subDomain buffer window. Hopefully I will have this all cleaned up in a couple of days.

**Closed** 2023-03-28 15:27 UTC
